/// A normalized, deterministic representation of the company's current
/// known state. Never raw documentation, never generated by the LLM —
/// this is what the LLM reasons over; it never sees CompanyContext or
/// raw HQ documents directly.
class CompanySnapshot {
  const CompanySnapshot({
    required this.company,
    required this.products,
    required this.capabilities,
    required this.assets,
    required this.websites,
    required this.analytics,
    required this.social,
    required this.services,
    required this.knownData,
    required this.missingData,
    required this.risks,
    required this.recommendationsInput,
  });

  final List<String> company;
  final List<String> products;
  final List<String> capabilities;
  final List<String> assets;
  final List<String> websites;
  final List<String> analytics;
  final List<String> social;
  final List<String> services;

  /// HQ categories that had at least one document (for example
  /// "Company", "Products", "Knowledge").
  final List<String> knownData;

  /// HQ categories with no documents at all — either because the
  /// category was empty, or because no connector for it exists yet (for
  /// example "Revenue", "CRM"). Never fabricated: an empty category is
  /// always reported here, never invented.
  final List<String> missingData;

  /// One deterministic risk statement per entry in [missingData].
  final List<String> risks;

  /// Known products and capabilities, prepared as raw material for the
  /// LLM's recommendations — not a recommendation itself.
  final List<String> recommendationsInput;
}
