import 'package:pharos_ai_runtime/company/department.dart';
import 'package:pharos_ai_runtime/company/department_context.dart';

/// One piece of traceability: which HQ category and document a known fact
/// came from. Exposed so future explainability features can show why a
/// recommendation was made, without the Runtime having to guess.
class Evidence {
  const Evidence({
    required this.category,
    required this.source,
    required this.confidence,
  });

  final String category;
  final String source;
  final String confidence;
}

/// A normalized, deterministic view of what one Department currently
/// knows. Never generated by the LLM: DepartmentContextBuilder decides
/// what a department can see, and DepartmentSnapshot only deduplicates it
/// and identifies what is known, missing, and blocked.
class DepartmentSnapshot {
  const DepartmentSnapshot({
    required this.department,
    required this.company,
    required this.knowledge,
    required this.products,
    required this.assets,
    required this.services,
    required this.websites,
    required this.social,
    required this.analytics,
    required this.knownData,
    required this.missingData,
    required this.blockedItems,
    required this.evidence,
  });

  factory DepartmentSnapshot.fromContext(DepartmentContext context) {
    final categories = <String, List<String>>{
      'Company': _dedupe(context.company),
      'Knowledge': _dedupe(context.knowledge),
      'Products': _dedupe(context.products),
      'Assets': _dedupe(context.assets),
      'Services': _dedupe(context.services),
      'Websites': _dedupe(context.websites),
      'Social': _dedupe(context.social),
      'Analytics': _dedupe(context.analytics),
    };

    final knownData = [
      for (final category in context.relevantCategories)
        if (categories[category]!.isNotEmpty) category,
    ];

    final missingData = [
      for (final category in context.relevantCategories)
        if (categories[category]!.isEmpty) category,
      ..._connectorGaps[context.department] ?? const <String>[],
    ];

    final blockedItems = [
      for (final category in missingData)
        '${context.department.displayName} cannot fully plan today '
            'without $category data — it is not yet connected.',
    ];

    final evidence = [
      for (final entry in categories.entries)
        for (final fact in entry.value)
          Evidence(
            category: entry.key,
            source: _sourceName(fact),
            confidence: 'High',
          ),
    ];

    return DepartmentSnapshot(
      department: context.department,
      company: categories['Company']!,
      knowledge: categories['Knowledge']!,
      products: categories['Products']!,
      assets: categories['Assets']!,
      services: categories['Services']!,
      websites: categories['Websites']!,
      social: categories['Social']!,
      analytics: categories['Analytics']!,
      knownData: knownData,
      missingData: missingData,
      blockedItems: blockedItems,
      evidence: evidence,
    );
  }

  final Department department;
  final List<String> company;
  final List<String> knowledge;
  final List<String> products;
  final List<String> assets;
  final List<String> services;
  final List<String> websites;
  final List<String> social;
  final List<String> analytics;

  /// Relevant categories that had at least one fact.
  final List<String> knownData;

  /// Relevant categories with nothing, plus this department's unconnected
  /// data sources. Never fabricated: always reported, never guessed.
  final List<String> missingData;

  /// One deterministic statement per entry in [missingData].
  final List<String> blockedItems;

  /// One entry per known fact, tracing it back to its HQ category and
  /// source document.
  final List<Evidence> evidence;

  /// HQ categories the Runtime has no connector for yet, per department.
  static const Map<Department, List<String>> _connectorGaps = {
    Department.executive: ['Revenue', 'CRM', 'Cross-Department Reporting'],
    Department.marketing: [
      'GA4',
      'Search Console',
      'Meta Ads',
      'Campaign History',
    ],
    Department.engineering: ['GitHub', 'CI/CD', 'Issue Tracker'],
    Department.sales: ['CRM', 'Lead Sources', 'Pipeline'],
    Department.operations: ['Workflow Automation', 'Support Tickets'],
    Department.finance: ['Revenue', 'Billing', 'Payment Providers'],
  };

  static List<String> _dedupe(List<String> entries) {
    final seen = <String>{};
    return [
      for (final entry in entries)
        if (seen.add(entry)) entry,
    ];
  }

  static String _sourceName(String fact) {
    final index = fact.indexOf(':');
    return index == -1 ? fact : fact.substring(0, index).trim();
  }
}
