import 'package:pharos_ai_runtime/company/department.dart';
import 'package:pharos_ai_runtime/knowledge/company_fact.dart';
import 'package:pharos_ai_runtime/knowledge/fact_type.dart';

/// One Department's structured, deterministic view of the Knowledge
/// Graph: only the facts it has a mandate over, plus which relevant fact
/// types are known versus missing. Never generated by the LLM.
class DepartmentFacts {
  const DepartmentFacts({
    required this.department,
    required this.facts,
    required this.knownTypes,
    required this.missingTypes,
  });

  final Department department;

  /// Facts of a type relevant to this department, visible to it.
  final List<CompanyFact> facts;

  /// Relevant fact types with at least one known fact.
  final List<FactType> knownTypes;

  /// Relevant fact types with no known fact — never guessed, always
  /// reported.
  final List<FactType> missingTypes;
}
