/// One deterministic statement backing a Decision (for example "Website
/// exists" or "Analytics unavailable"). Never generated by the LLM.
class DecisionReason {
  const DecisionReason(this.statement);

  final String statement;
}
